//
// DemoPost.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model containing Info of /Post */

public struct DemoPost: Codable {

    public var userId: Int?
    public var _id: Int?
    public var title: String?
    public var body: String?

    public init(userId: Int?, _id: Int?, title: String?, body: String?) {
        self.userId = userId
        self._id = _id
        self.title = title
        self.body = body
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "UserId"
        case _id = "id"
        case title
        case body
    }


}

