# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KeyChain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KeyChain
  pod 'KeychainSwift', '~> 19.0'
  target 'KeyChainTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KeyChainUITests' do
    # Pods for testing
  end

end