//
// DemoAlbum.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model containing Info of /Album */

public struct DemoAlbum: Codable {

    public var userId: Int?
    public var _id: Int?
    public var title: String?

    public init(userId: Int?, _id: Int?, title: String?) {
        self.userId = userId
        self._id = _id
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case userId = "UserId"
        case _id = "id"
        case title
    }


}

