# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AlamofirePod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofirePod
pod 'Alamofire'

  target 'AlamofirePodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlamofirePodUITests' do
    # Pods for testing
  end

end
