//
// CalendrificAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class CalendrificAPI {
    /**

     - parameter aPIKey: (query)  
     - parameter country: (query)  
     - parameter year: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func holidaysGet(aPIKey: String, country: String, year: Int, completion: @escaping ((_ data: JSONValue?,_ error: Error?) -> Void)) {
        holidaysGetWithRequestBuilder(aPIKey: aPIKey, country: country, year: year).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /holidays
     - Returns list holidays with specfied Parameters.
     - examples: [{contentType=application/json, example="{}"}]
     
     - parameter aPIKey: (query)  
     - parameter country: (query)  
     - parameter year: (query)  

     - returns: RequestBuilder<JSONValue> 
     */
    open class func holidaysGetWithRequestBuilder(aPIKey: String, country: String, year: Int) -> RequestBuilder<JSONValue> {
        let path = "/holidays"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "API_Key": aPIKey, 
            "country": country, 
            "year": year.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<JSONValue>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
