# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AFNetworkingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AFNetworkingApp

pod 'AFNetworking', '~> 4.0'

  target 'AFNetworkingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFNetworkingAppUITests' do
    # Pods for testing
  end

end
