# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Login Form' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'IQKeyboardManager'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  # Pods for Login Form

  target 'Login FormTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Login FormUITests' do
    # Pods for testing
  end

end
