//
// DateTime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tells the exact date in parameters of Year,Month and Day. */

public struct DateTime: Codable {

    public var year: Int?
    public var month: Int?
    public var day: Int?

    public init(year: Int?, month: Int?, day: Int?) {
        self.year = year
        self.month = month
        self.day = day
    }


}

