//
// Date.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Tells the Date of holiday. */

public struct Date: Codable {

    public var iso: String?
    public var datetime: JSONValue?

    public init(iso: String?, datetime: JSONValue?) {
        self.iso = iso
        self.datetime = datetime
    }


}

