//
// HolidayArray.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Model Containing Array of dictionary which includes details */

public struct HolidayArray: Codable {

    public var name: String?
    public var _description: String?
    public var date: JSONValue?
    public var type: [ERRORUNKNOWN]?
    public var location: String?
    public var states: String?

    public init(name: String?, _description: String?, date: JSONValue?, type: [ERRORUNKNOWN]?, location: String?, states: String?) {
        self.name = name
        self._description = _description
        self.date = date
        self.type = type
        self.location = location
        self.states = states
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case date
        case type
        case location
        case states
    }


}

