//
// Meta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Meta data of the API */

public struct Meta: Codable {

    public var code: Int?
    public var errorType: String?
    public var errorDetail: String?

    public init(code: Int?, errorType: String?, errorDetail: String?) {
        self.code = code
        self.errorType = errorType
        self.errorDetail = errorDetail
    }

    public enum CodingKeys: String, CodingKey { 
        case code
        case errorType = "error_type"
        case errorDetail = "error_detail"
    }


}

